### ISSUE TITLE
Connection Failed with Taranis X-Lite Pro + Radiomaster ELRS Nano

### ISSUE THREAD

**Issue by druckgott** [RomanLut/android-taranis-smartport-telemetry#41]
Hi,

I get a connection Failed with the Taranix X-Lite Pro + Radimaster ELRS Nano, is there a posiblitty to debug something to find out more why the conneciton get lost. I checkt LO Bluetooth and normal Bluetooth.

Can you help me?
With Opentx it worked for me with the Old version from CrazyDude, but it was with Frsky. Now I´m on Edgetx and Expresslrs.

**Comment by RomanLut** [comment]
Unfortunatelly there is no way to debug bluetooth issues. If you have problems with bluetooth connection, try setting telemetry mirror to USB VCP in Edge TX and connecting phone to Taranis X-Lite Pro using usb cable.

**Comment by druckgott** [comment]
I cant find this point in my taranis x-lite. I only see Trainer: Master and Slave. There is nothing with telemetry. on Opentx it was availibe.
Taranis has integrated bluetooth modul

**Comment by druckgott** [comment]
Ok I get it working. I have to Set in Page 2/11 on SETUP for Trainer --> Mode --> OFF then it works with internal modul.
