### ISSUE TITLE
Logs not shown in hx1. 5

### ISSUE THREAD

**Issue by druckgott** [RomanLut/android-taranis-smartport-telemetry#43]
Hi I have logs in the folder which I already replayed. One day later I want to show it to my friends but it's not working the list in the app is empty.

Here are some. Pictures. If you need more information please. Let me. Know. It's really. A cool. App. 
![Screenshot_20230613_070446_com huawei filemanager](https://github.com/RomanLut/android-taranis-smartport-telemetry/assets/18383738/2140a4b8-6241-458f-b350-a24e91951db5)
![Screenshot_20230613_070417_crazydude com telemetry](https://github.com/RomanLut/android-taranis-smartport-telemetry/assets/18383738/daf42e35-5ceb-438b-8db0-d117ca7f3a93)

**Comment by RomanLut** [comment]
csv can be written but can not be replayed currently.
Correct logs have .log extention.

**Comment by druckgott** [comment]
I see that it works on the same Day where you do the flight, but on the next day it's not any more working

**Comment by RomanLut** [comment]
Is there a .log files in this folder next day?
If not, then a guess some "Optimizer" application deletes them to free space by "deleting unnecessary files". You have to disable it.

**Comment by druckgott** [comment]
Ok no there is now one. Is it maybe posible to make a switch ore to define extension name by the app to maybe do not use log maybe log2 ore something like this.
How CAN I find out which app remove this? I do not aktivated anything on my Huawei P20

**Comment by RomanLut** [comment]
O, I think I will change extension to .tlm for the new logs in the next release, probably next week.

**Comment by RomanLut** [comment]
Implemented in v 1.6

**Comment by druckgott** [comment]
Perfekt thx
