### ISSUE TITLE
Feature Request: show telemetry protocol

### ISSUE THREAD

**Issue by jiri-jirus** [RomanLut/android-taranis-smartport-telemetry#44]
Hello, would it be possible to display in app what telemetry protocol is the app decoding? S.port / CRSF / Mavlink / etc. 

Thanks

**Comment by jiri-jirus** [comment]
@RomanLut hello can i do something for this issue?

**Comment by RomanLut** [comment]
Already implemented for playback.
I will implement if for connections in a week.

**Comment by RomanLut** [comment]
Implemented in v 1.6
