### ISSUE TITLE
Feature Request: add FrSky telemetry decode from Multi-Module telemetry

### ISSUE THREAD

**Issue by Maarten112** [RomanLut/android-taranis-smartport-telemetry#46]
Hi guys, 

Currently FrSky Telemetry doesn't work when coming from Multi-Module, since the Multi-Module adds some packets before the real telemetry. 

Please see my comment here: https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/issues/104#issuecomment-954882214

Would be so nice if someone could add this to the decoders!

**Comment by jiri-jirus** [comment]
i hope this will not happen anytime

**Comment by Maarten112** [comment]
> i hope this will not happen anytime

Is this a typo or do you have some specific reasons why you say ' I hope this will NOT happen anytime ?

**Comment by RomanLut** [comment]
Implemented in v 1.6
