### ISSUE TITLE
Missing license and copyright file

### ISSUE THREAD

**Issue by Adamo198** [RomanLut/android-taranis-smartport-telemetry#48]
Hello,

On behalf of a Polish drone company, I would like to request the addition of a file related to the license, specifying the right to use the software. We want to use it commercially as a basis for developing their software to enhance its capabilities. Without a clear declaration regarding the license, we can't do it. I would be very happy to enter into a conversation in this regard. Do you have any contact to original app creator, CrazyDude1994?

**Comment by RomanLut** [comment]
Yu can try to reach original author in it's telegram group
https://t.me/joinchat/Gf03BFXI2e48WMvzjLeIjw
